apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-ci
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: osm-ca
  namespace: issuerns
spec:
  isCA: true
  commonName: osm-system
  secretName: osm-ca

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  usages:
    - server auth
    - client auth

  issuerRef:
    name: selfsigned-ci
    kind: ClusterIssuer
    group: cert-manager.io